# Arrays vs Lists

In [8]:
import numpy as np

In [7]:
L = [1, 2, 3]

In [9]:
A = np.array([1, 2, 3])

In [11]:
for e in L:
    print(e)

1
2
3


In [12]:
for e in A:
    print(e)

1
2
3


Adding a new item to a list

In [13]:
L.append(4)

In [15]:
L

[1, 2, 3, 4]

In [17]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [19]:
L + [ 5 ]

[1, 2, 3, 4, 5]

In [22]:
A + np.array([4])

array([5, 6, 7])

In [24]:
A + np.array([5, 6, 7])

array([ 6,  8, 10])

In [27]:
A + np.array([4, 5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## Scalar and Multiplication

In [29]:
2 * A

array([2, 4, 6])

In [31]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [33]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [35]:
L2 = []
for e in L:
    L2.append(e + 3 )
L2

[4, 5, 6, 7]

In [45]:
L2 = [ e + 3 for e in L ]