# Arrays vs Lists

In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]

In [3]:
A = np.array([1, 2, 3])

In [4]:
for e in L:
    print(e)

1
2
3


In [5]:
for e in A:
    print(e)

1
2
3


Adding a new item to a list

In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [8]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
L + [ 5 ]

[1, 2, 3, 4, 5]

In [10]:
A + np.array([4])

array([5, 6, 7])

In [11]:
A + np.array([5, 6, 7])

array([ 6,  8, 10])

In [12]:
A + np.array([4, 5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## Scalar and Multiplication

In [13]:
2 * A

array([2, 4, 6])

In [14]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
L2 = []
for e in L:
    L2.append(e + 3 )
L2

[4, 5, 6, 7]

In [17]:
L2 = [ e + 3 for e in L ]
L2

[4, 5, 6, 7]

In [18]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [19]:
L2 = []
for e in L:
    L2.append(e**2)

In [20]:
L2

[1, 4, 9, 16]

In [21]:
A**2

array([1, 4, 9])

In [23]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [25]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [26]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [27]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [29]:
a = np.array([1, 2])
b = np.array([3, 4])

In [30]:
dot = 0
for e, f in zip(a, b):
    dot += e * f
dot

11

In [31]:
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
dot

11

In [32]:
a * b

array([3, 8])

In [34]:
np.sum(a * b)

11

In [35]:
(a * b).sum()

11

In [36]:
np.dot(a, b)

11

In [37]:
a.dot(b)

11

In [38]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [39]:
amag = np.sqrt(( a * a ).sum())

In [40]:
amag

2.23606797749979

In [41]:
np.linalg.norm(a)

2.23606797749979

In [42]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [43]:
angle = np.arccos(cosangle)
angle

0.17985349979247847